name: Build and Deploy Book
on:
  push:
    branches:
    - main
jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Install dependencies
      run: python -m pip install --upgrade pip; pip install -r requirements.txt; pip install git+https://github.com/papsebestyen/datazimmer.git
    - name: Setup Git
      run: git config --global init.defaultBranch main;git config --global user.email
        "leo@dumbartonserum.com";git config --global user.name "Leo Dumbarton";git
        pull --tags
    - name: Setup matplotlib
      run: ipython profile create;
        printf 'c = get_config()\nc.IPKernelApp.matplotlib = "inline"' 
        > ~/.ipython/profile_default/ipython_kernel_config.py
    - name: Build the book
      run: dz load-explorer-data && dz build-explorer
      env:
        ZIMMER_FULL_AUTH: ${{ secrets.ZIMMER_FULL_AUTH }}
        GIT_HTTPS_TOKEN: ${{ secrets.GIT_HTTPS_TOKEN }}
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: book/_build/html
